apiVersion: v1
kind: ConfigMap
metadata:
  name: cast-db-configmap
  labels:
    app: cast-db
data:
    POSTGRES_DB: cast_db_dev
    POSTGRES_USER: cast_db_username
    POSTGRES_PASSWORD: cast_db_password