apiVersion: v1
kind: PersistentVolume
metadata:
  name: cast-db-pv
  labels:
    type: local
    app: cast-db
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres_data_cast