apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-deployment
  labels:
    app: cast-service
spec:
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: blynhelb/castservice:{{ .Values.tag }}
        ports:
          - containerPort: 8080
        command: ["uvicorn"]
        args: ["app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]