apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-db-configmap
  labels:
    app: movie-db
data:
    POSTGRES_DB: movie_db_dev
    POSTGRES_USER: movie_db_username
    POSTGRES_PASSWORD: movie_db_password