apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db-statefulset
  labels:
    app: movie-db
spec:
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: movie-db
        image: postgres:12.1-alpine
        volumeMounts:
          - name: postgresdata
            mountPath: /var/lib/postgresql/data/
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name:  movie-db-rootpass
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: movie-db-rootpass
                key: password           
        envFrom:
          - configMapRef:
              name: movie-db-configmap
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: movie-db-pvc