apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db-statefulset
  labels:
    app: movie-db
spec:
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: movie-db
        image: postgres:12.1-alpine
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: postgresdata
            mountPath: /var/lib/postgresql/data/         
        envFrom:
          - configMapRef:
              name: movie-db-configmap
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: movie-db-pvc