apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-config
  labels:
    app: movie-service
data:
    DATABASE_URI: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
    CAST_SERVICE_HOST_URL: http://cast_service:8000/api/v1/casts/