apiVersion: v1
kind: PersistentVolume
metadata:
  name: movie-db-pv
  labels:
    type: local
    app: movie-db
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres_data_movie